spring:
  profiles.active: local
  application.name: '@project.name@'
  output.ansi.enabled: always
  main.banner-mode: log

server.port: 8080

management:
  endpoints:
    web:
      base-path: /monitor
      exposure.include: health,info,metrics
  endpoint.health.show-details: always
  info:
    build.enabled: true
    env.enabled: true

info.application:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  build-timestamp: '@project.build.timestamp@'

springdoc:
  swagger-ui:
    path: /doc
    url: /v3/api-docs.yaml