apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn
spec:
  selector:
    matchLabels:
      app: cdn
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
        - image: nginx:alpine
          name: cdn
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cdn-config-persistent-volume
              mountPath: /etc/nginx/nginx.conf
            - name: cdn-persistent-volume
              mountPath: /tech-challenge/static
      volumes:
        - name: cdn-config-persistent-volume
          persistentVolumeClaim:
            claimName: cdn-config-persistent-volume-claim
        - name: cdn-persistent-volume
          persistentVolumeClaim:
            claimName: cdn-persistent-volume-claim