version: "3.9"

services:
  mysql:
    container_name: mysql
    image: tech-challenge-mysql
    build:
      context: ../docker/mysql
      dockerfile: ../mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "P@55W0rD"
    ports:
      - "3366:3306"
    volumes:
      - ../docker/mysql/data:/var/lib/mysql
    networks:
      - tech-challenge-network

  redis:
    image: library/redis:6-alpine
    platform: linux/amd64
    ports:
      - "6380:6379"
    networks:
      - tech-challenge-network

  cdn:
    container_name: cdn
    image: tech-challenge-cdn
    build:
      context: ../docker/nginx
      dockerfile: ../nginx/Dockerfile
    restart: always
    ports:
      - "8888:8080"

networks:
  tech-challenge-network:
    driver: bridge

