version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "P@55W0rD"
    ports:
      - "3366:3306"
    volumes:
      - ${PWD}/docker/mysql/data:/var/lib/mysql
      - ${PWD}/docker/mysql/script:/opt/scripts
      - ${PWD}/docker/mysql/script/setup.sql:/docker-entrypoint-initdb.d/1.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tech-challenge-network

networks:
  tech-challenge-network:
    driver: bridge

