apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: container-app
          image: fiapsoat2grupo13/tech-challenge-service
          ports:
            - containerPort: 8080
          env:
            - name: "spring.profiles.active"
              value: "prod"
            - name: "server.port"
              value: "8080"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /monitor/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /monitor/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 60