name: DeployBuild and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

env:
  IMAGE_REPOSITORY: fiapsoat2grupo13
  IMAGE_NAME: tech-challenge-service
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew build

      - run: gradle build --dry-run # just test build configuration
      - run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}