name: Build and Push Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        run: ./gradlew build

      - run: gradle build --dry-run # just test build configuration
      - run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"