apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  labels:
    type: mysql-persistent-volume
spec:
  storageClassName: mysql-persistent-volume-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/07.000325/workspace/fiap/tech-challenge/infra/kubernetes/mysql/data