apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
  labels:
    name: mysql-persistent-volume-claim
spec:
  storageClassName: mysql-persistent-volume-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi